---
title: "Untitled"
format: html
---
### script analysing POMS T cells subsetted from main object
### LOAD PACKAGES
```{python}
import scanpy as sc
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import scvi
import harmonypy as hm
import os
import celltypist
from celltypist import models
import re
import pertpy as pt
import muon as mu
import mudata as md
import sys
print(sys.executable) 
import torch
import pandas as pd
from plotnine import *
from scipy.stats import f_oneway
```

### LOAD DATA AND ASSESS
```{python}
adata = mu.read(filename = "Tcell_analysis/POMS_CITE_processed_4-5_Tcells.h5mu")
(sys.getsizeof(adata) / (1024**3))
```

```{python}
adata
citeseq_proteins =adata.mod["prot"].var.copy()
```

```{python}
sc.pl.umap(
    adata.mod["rna"],
    color=["CD3D", "CD8A", "CD4", "FOXP3"]
)
```
```{python}
mu.pl.embedding(adata, basis="rna:X_umap", layer = "rna:logcounts", color = ["rna:CD3D", "rna:CD79A", "rna:FOXP3", "rna:LYZ"], size = 5)
```

```{python}
meta_cols = adata.mod["rna"].obs.columns
```
```{python}
sc.pl.umap(
    adata.mod["rna"],
    color="celltypist_label_immune-coarse",size=5
)
```
```{python}
sc.pl.dotplot(adata.mod["rna"], var_names = ["CD3D", "CD3E", "CD3G", "CD8A", "CD4", "FOXP3"], groupby = "patient_nice")
```

### based on Tim's script (sc_analysis_4-CombineSplit.ipynb) it appears rna and prot get split, rna processed and then re-combined afterwards
### i will do the same (+ running the steps won't work on the combined data anyway without adjustments!)
```{python}
rna = adata.mod["rna"]
pro = adata.mod["prot"]
```

### remove full adata to save memory
```{python}
del(adata)
```

### RE-RUN PROCESSING STEPS FOR SUB-CLUSTERING

## make sure X is set to the counts and then normalise, before saving the logcounts again
```{python}
rna.X = rna.layers["counts"].copy()
sc.pp.normalize_total(rna)
sc.pp.log1p(rna)
rna.layers["logcounts"] = rna.X.copy()
```

```{python}
sc.pp.highly_variable_genes(
        rna, 
        n_top_genes=2000, 
        flavor="cell_ranger", 
        batch_key='patient_nice', 
        layer = 'logcounts',
        subset = False
    )
sc.pp.pca(rna, svd_solver="arpack", mask_var="highly_variable", random_state=2025)
```

### set batch key (what we want to correct on)
### get pcs from object and run harmony on the pca embedding
### then add corrected pcs back into object
```{python}
batch_key = ["chemistry", "pool"]
pcs = rna.obsm['X_pca']
print(pcs.shape)
harmony_out = hm.run_harmony(pcs, rna.obs, batch_key)
rna.obsm['X_pca_harmony'] = harmony_out.Z_corr
```

### calculate embedding with corrected pcs
```{python}
sc.pp.neighbors(rna, use_rep='X_pca_harmony')
sc.tl.umap(rna)
sc.tl.leiden(rna)
```

### save rna object
```{python}
import anndata as ad
ad.settings.allow_write_nullable_strings = True
rna.write(filename = "poms_Tcells_subclustered_RNA.h5ad")
```

### combine with protein data and save as whole object

```{python}
meta_cols = rna.obs.columns
```

### inspect umap
```{python}
sc.pl.umap(rna, color = ["age", "pool", "celltypist_label_immune-fine", "celltypist_label_fetal"], size = 5, ncols=2)
```

### run mumltiple clustering resolutions
```{python}
 for res in [0.5, 0.8, 1, 1.2, 1.5]:
    sc.tl.leiden(rna, key_added = "leiden_res_" + str(res), resolution = res)
```

```{python}
sc.pl.umap(rna, color = ["leiden_res_0.5", "leiden_res_0.8", "leiden_res_1.2", "leiden_res_1.5"], size = 5, ncols=2)
```

### leiden clustering was time-consuming (at least 1 hour) so save again
```{python}
rna.write(filename = "poms_Tcells_subclustered_RNA.h5ad")
```